# -*- coding: utf-8 -*-
"""모델학습v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RSwL-TGAXOmtqoDlZHcVcSgyNSCSfbhA
"""

!apt-get update
!apt-get install -y fonts-noto-cjk

# -*- coding: utf-8 -*-
"""
모델학습_v3_정상화.py

[v2 대비 수정 사항]
1. tokenizer 정의 누락 문제 해결 -> 셀 5에 명시적으로 추가
2. is_strict_finance 함수명 불일치 해결 -> is_strict_finance로 통일, 정의/호출 일치
3. FINANCE_KEYWORDS / EXCLUDE_KEYWORDS -> 실제 검증된 값으로 확정 (아래 참고)
4. 각 단계마다 검증 로그 추가 (개수, 샘플 미리보기) -> 재현성 확보
5. train/val 분할 시 인덱스 저장 -> 나중에 오분류 분석 시 원본 텍스트 역추적 가능

[확정된 필터링 기준]
- FINANCE_KEYWORDS: 실제 학습에 쓰인 15개 버전 (펀드/주식/투자/보험/보증보험 포함)
- EXCLUDE_KEYWORDS: 더 엄격한 15개 버전 (교육 + 상품/서비스 전부 포함)
  -> 이렇게 하면 v2 실제 학습보다 더 좁게 필터링되어 정상 데이터 개수가 줄어들 수 있음
  -> [3/4] 필터링 단계 로그에서 몇 개가 남는지 반드시 확인할 것

[단계별 실행 위치 가이드]
  Colab 셀 1: 라이브러리 설치
  Colab 셀 2: Drive 마운트 + 정규화 함수 정의
  Colab 셀 3: 데이터 로드 (엄격한 필터링 적용)
  Colab 셀 4: 정규화 + Train/Val 분할
  Colab 셀 5: tokenizer 로드 + 토크나이제이션 + Dataset
  Colab 셀 6: 모델 + Trainer 구성
  Colab 셀 7: 학습 실행
  Colab 셀 8: 오분류 분석 (학습 직후 바로 실행 가능)
"""

# ============================================================================
# [셀 1] 라이브러리 설치
# ============================================================================

import subprocess
import sys

print("필요한 라이브러리 설치 중...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "transformers==4.44.2", "peft"])
print("✅ 설치 완료\n")

# ============================================================================
# [셀 2] Drive 마운트 + 정규화 함수 정의
# ============================================================================

from google.colab import drive
drive.mount('/content/drive')

import os
import re
import random
import zipfile
import time
import shutil
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from transformers import (
    ElectraTokenizer, ElectraForSequenceClassification,
    TrainingArguments, Trainer
)

print("✅ Drive 마운트 완료\n")

# ==================== 정규화 함수 정의 ====================

_AIHUB_FILLER_WHITELIST = ['아', '어', '음', '그', '뭐', '저', '막', '좀']
_AIHUB_FILLER_PATTERN = re.compile(
    r'\b(?:[a-z]|' + '|'.join(_AIHUB_FILLER_WHITELIST) + r')/'
)


def merge_consecutive_dual_notation(text: str) -> str:
    pattern = r'((?:\(\d+\)/\([^)]*\)\s*에?\s*){2,}\(\d+\)/\([^)]*\))'
    def merge_group(match):
        numbers = re.findall(r'\((\d+)\)/\([^)]*\)', match.group(1))
        return ''.join(numbers)
    return re.sub(pattern, merge_group, text)


def normalize_dual_notation(text: str) -> str:
    pattern = r'\((\d[\w]*)\)/\([^)]*\)'
    return re.sub(pattern, r'\1', text)


def merge_spaced_digits(text: str) -> str:
    pattern = r'(?:\d\s){4,}\d'
    return re.sub(pattern, lambda m: m.group(0).replace(' ', ''), text)


def remove_correction_marker(text: str) -> str:
    return text.replace('+', ' ')


def remove_noise_markup(text: str) -> str:
    pattern = r'\(\([^)]*\)\)'
    return re.sub(pattern, ' ', text)


def remove_aihub_filler_markup(text: str) -> str:
    return _AIHUB_FILLER_PATTERN.sub(' ', text)


def remove_masking_marker(text: str) -> str:
    pattern = r'\(삐-?\)'
    return re.sub(pattern, ' ', text)


def strip_speaker_label(text: str) -> str:
    text = re.sub(r'(피해자|사기범)\s*:\s*', ' ', text)
    return text


def clean_whitespace(text: str) -> str:
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def normalize_finance_text(text: str) -> str:
    """AI Hub + his_voice 통합 정규화"""
    text = merge_consecutive_dual_notation(text)
    text = normalize_dual_notation(text)
    text = merge_spaced_digits(text)
    text = remove_correction_marker(text)
    text = remove_noise_markup(text)
    text = remove_aihub_filler_markup(text)
    text = remove_masking_marker(text)
    text = strip_speaker_label(text)
    text = clean_whitespace(text)
    return text


print("✅ 정규화 함수 정의 완료\n")

# ============================================================================
# [셀 3] 데이터 로드 (엄격한 도메인 필터링)
# ============================================================================

def load_txt_files(folder_path, label):
    data = []
    files = [f for f in os.listdir(folder_path) if f.endswith('.txt')]
    for fname in files:
        path = os.path.join(folder_path, fname)
        with open(path, 'r', encoding='utf-8') as f:
            text = f.read()
        data.append({'text': text, 'label': label, 'source': fname})
    return data


print("=" * 70)
print("데이터 로드 중...")
print("=" * 70 + "\n")

start_time = time.time()

# [1] 사기 데이터 (his_voice)
print("[1/4] his_voice (사기 데이터) 로드...")
his_voice_path = "/content/drive/MyDrive/his_voice"
data_path = os.path.join(his_voice_path, "data")

fraud_data = load_txt_files(os.path.join(data_path, "impersonation"), label=1)
fraud_data += load_txt_files(os.path.join(data_path, "loanScam"), label=1)
print(f"✅ 사기 데이터: {len(fraud_data)}개\n")

# [2] 정상 데이터 (AI Hub zip)
print("[2/4] AI Hub (정상 데이터) zip 압축해제...")
aihub_zip_path = "/content/drive/MyDrive/voice_pishing_text_merged/상담음성_재병합_결과.zip"
extract_path = "/tmp/aihub_extract_new"

if os.path.exists(extract_path):
    shutil.rmtree(extract_path)
os.makedirs(extract_path)

with zipfile.ZipFile(aihub_zip_path, 'r') as zf:
    zf.extractall(extract_path)

normal_data = []
files = [f for f in os.listdir(extract_path) if f.endswith('.txt')]
print(f"  추출된 파일 확인: {len(files)}개")

for fname in files:
    path = os.path.join(extract_path, fname)
    try:
        with open(path, 'r', encoding='utf-8') as f:
            text = f.read()
        normal_data.append({'text': text, 'label': 0, 'source': fname})
    except Exception as e:
        print(f"  경고: {fname} 읽기 실패 - {e}")

print(f"✅ 정상 데이터: {len(normal_data)}개 (압축해제 후)\n")

# 검증: 이 개수가 49,839와 일치하는지 확인 (데이터 손실 재발 여부 체크)
if len(normal_data) != 49839:
    print(f"⚠️ 경고: 예상 개수(49,839)와 다름 -> 데이터 손실 재발 가능성, 원인 재확인 필요\n")
else:
    print(f"✅ 예상 개수(49,839)와 일치 -> 데이터 손실 문제 없음 확인됨\n")

# [3] 엄격한 도메인 필터링
print("[3/4] 도메인 필터링 (금융거래만, 교육/상품/서비스 제외 - 엄격 버전)...")

# 확정: 실제 학습 버전 (펀드/주식/투자/보험/보증보험 포함, 15개)
FINANCE_KEYWORDS_STRICT = [
    '은행', '계좌', '통장', '이체', '송금', '대출', '신용카드', '체크카드',
    '적금', '예금', '펀드', '주식', '투자', '보험', '보증보험'
]

# 확정: 더 엄격한 버전 (교육 + 상품/서비스 전부, 15개)
EXCLUDE_KEYWORDS = [
    '교육', '학습', '강의', '상담사',
    '클러치', '그래픽카드', '자동차',
    '택배', '배송', '구매', '상품',
    '게임', '영화', '클럽', '카페'
]


def is_strict_finance(text):
    """엄격한 금융 필터: 금융키워드 포함 AND 교육/상품/서비스키워드 제외"""
    has_finance = any(kw in text for kw in FINANCE_KEYWORDS_STRICT)
    has_exclude = any(kw in text for kw in EXCLUDE_KEYWORDS)
    return has_finance and not has_exclude


# 필터링 적용
finance_normal = [d for d in normal_data if is_strict_finance(d['text'])]
print(f"✅ 필터링 후 금융 상담: {len(finance_normal)}개 (원본 {len(normal_data)}개 중)")
print(f"   필터링 비율: {len(finance_normal) / len(normal_data):.2%}\n")

# 검증: 필터링 결과가 너무 적으면 경고 (Hard Negative 테스트에 쓸 수 있는 양인지)
if len(finance_normal) < len(fraud_data):
    print(f"⚠️ 경고: 필터링된 정상 데이터({len(finance_normal)}개)가 사기 데이터({len(fraud_data)}개)보다 적음")
    print(f"   -> EXCLUDE_KEYWORDS가 너무 엄격했을 가능성. 클래스 균형 조정 시 사기 데이터 쪽이 줄어듦\n")

# [4] 클래스 균형
print("[4/4] 클래스 균형 조정...")
random.seed(42)

n_before_fraud = len(fraud_data)
n_before_normal = len(finance_normal)

if len(finance_normal) > len(fraud_data):
    finance_normal = random.sample(finance_normal, len(fraud_data))
elif len(fraud_data) > len(finance_normal):
    fraud_data = random.sample(fraud_data, len(finance_normal))

print(f"✅ 최종 데이터:")
print(f"   - 사기(1): {len(fraud_data)}개 (조정 전 {n_before_fraud}개)")
print(f"   - 정상(0): {len(finance_normal)}개 (조정 전 {n_before_normal}개)")
print(f"   - 합계: {len(fraud_data) + len(finance_normal)}개\n")

elapsed = time.time() - start_time
print(f"📊 데이터 로드 완료 ({elapsed:.1f}초)\n\n")

# ============================================================================
# [셀 4] 정규화 + Train/Val 분할
# ============================================================================

print("=" * 70)
print("정규화 및 학습 데이터 준비")
print("=" * 70 + "\n")

start_time = time.time()

# 정규화
all_data = fraud_data + finance_normal
print(f"정규화 적용 중 ({len(all_data)}개)...")
for i, item in enumerate(all_data):
    if (i + 1) % 100 == 0:
        print(f"  {i+1}/{len(all_data)}")
    item['text'] = normalize_finance_text(item['text'])
print("✅ 정규화 완료\n")

# 검증: 정규화 후 빈 텍스트가 생겼는지 확인 (정규화 과정에서 내용이 다 지워지는 엣지 케이스 방지)
empty_after_norm = sum(1 for item in all_data if len(item['text'].strip()) == 0)
if empty_after_norm > 0:
    print(f"⚠️ 경고: 정규화 후 빈 텍스트 {empty_after_norm}개 발견 -> 해당 샘플 확인 필요\n")

# 데이터프레임 + Train/Val 분할 (원본 인덱스 보존 -> 나중에 역추적용)
df = pd.DataFrame(all_data).reset_index(drop=True)
df['orig_idx'] = df.index  # 오분류 분석 시 원본 source 파일명 역추적용

print("라벨 분포:")
print(df['label'].value_counts())
print()

train_df, val_df = train_test_split(
    df, test_size=0.2, random_state=42, stratify=df['label']
)
train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)

print(f"✅ Train: {len(train_df)}, Val: {len(val_df)}")
print(f"   Train 라벨 분포: {dict(train_df['label'].value_counts())}")
print(f"   Val 라벨 분포  : {dict(val_df['label'].value_counts())}\n")

elapsed = time.time() - start_time
print(f"📊 준비 완료 ({elapsed:.1f}초)\n\n")

# ============================================================================
# [셀 5] tokenizer 로드 + 토크나이제이션 + Dataset
# ============================================================================
# ★ v2에서 누락됐던 부분 - 명시적으로 추가

print("=" * 70)
print("Tokenizer 로드 및 토크나이제이션")
print("=" * 70 + "\n")

start_time = time.time()

MODEL_NAME = "skplanet/dialog-koelectra-small-discriminator"

print(f"Tokenizer 로드: {MODEL_NAME}")
tokenizer = ElectraTokenizer.from_pretrained(MODEL_NAME)
print(f"✅ Tokenizer 로드 완료 (vocab size: {tokenizer.vocab_size})\n")

MAX_LENGTH = 128

train_encodings = tokenizer(
    train_df['text'].tolist(),
    truncation=True,
    padding=True,
    max_length=MAX_LENGTH
)
val_encodings = tokenizer(
    val_df['text'].tolist(),
    truncation=True,
    padding=True,
    max_length=MAX_LENGTH
)

print(f"✅ 토크나이제이션 완료 (max_length={MAX_LENGTH})\n")


# Dataset 클래스
class VoicePhishingDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item


train_dataset = VoicePhishingDataset(train_encodings, train_df['label'].tolist())
val_dataset = VoicePhishingDataset(val_encodings, val_df['label'].tolist())

print("✅ Dataset 구성 완료\n")

elapsed = time.time() - start_time
print(f"📊 토크나이제이션 완료 ({elapsed:.1f}초)\n\n")

# ============================================================================
# [셀 6] 모델 + Trainer 구성
# ============================================================================

print("=" * 70)
print("모델 로드 및 Trainer 구성")
print("=" * 70 + "\n")

print("모델 로드...")
model = ElectraForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)
print("✅ 모델 로드 완료\n")


def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, predictions, average='binary'
    )
    acc = accuracy_score(labels, predictions)
    return {
        'accuracy': acc,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }


print("Trainer 구성...")
OUTPUT_DIR = "/content/drive/MyDrive/results_v3_normalized"

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    save_safetensors=False,
    logging_steps=10,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    tokenizer=tokenizer,  # ★ v2에서 빠졌던 부분 - 명시적으로 전달
)

os.environ["WANDB_DISABLED"] = "true"

print("✅ Trainer 구성 완료\n\n")

# ============================================================================
# [셀 7] 학습 실행
# ============================================================================

print("=" * 70)
print("🚀 학습 시작")
print("=" * 70 + "\n")

trainer.train()

print("\n" + "=" * 70)
print("✅ 학습 완료")
print("=" * 70)
print(f"\n📁 모델 저장 위치: {OUTPUT_DIR}")

# 학습 설정도 함께 저장 -> 재현성 확보 (나중에 "이 모델이 어떤 필터링으로 나왔는지" 추적 가능)
import json
run_metadata = {
    "model_name": MODEL_NAME,
    "max_length": MAX_LENGTH,
    "finance_keywords": FINANCE_KEYWORDS_STRICT,
    "exclude_keywords": EXCLUDE_KEYWORDS,
    "n_fraud": len(fraud_data),
    "n_normal": len(finance_normal),
    "n_train": len(train_df),
    "n_val": len(val_df),
    "aihub_raw_count": len(normal_data),
}
with open(os.path.join(OUTPUT_DIR, "run_metadata.json"), "w", encoding="utf-8") as f:
    json.dump(run_metadata, f, ensure_ascii=False, indent=2)
print(f"📄 학습 메타데이터 저장: {os.path.join(OUTPUT_DIR, 'run_metadata.json')}\n")

# ============================================================================
# [셀 8] 오분류 분석 (학습 직후 바로 실행)
# ============================================================================

print("=" * 70)
print("오분류 샘플 분석")
print("=" * 70 + "\n")

eval_ds = trainer.eval_dataset

print(f"Validation set 전체 개수: {len(eval_ds)}")
labels_arr = np.array(eval_ds.labels)
unique, counts = np.unique(labels_arr, return_counts=True)
print("라벨별 개수:")
for u, c in zip(unique, counts):
    tag = "사기(1)" if u == 1 else "정상(0)"
    print(f"  {tag}: {c}개")
print()

pred_output = trainer.predict(eval_ds)
logits = pred_output.predictions
probs = np.exp(logits) / np.exp(logits).sum(axis=-1, keepdims=True)
pred_labels = np.argmax(logits, axis=-1)
true_labels = pred_output.label_ids
confidences = probs.max(axis=-1)

# tokenizer는 셀 5에서 이미 정의되어 있으므로 바로 사용 가능
texts = [tokenizer.decode(ids, skip_special_tokens=True) for ids in eval_ds.encodings["input_ids"]]

result_df = pd.DataFrame({
    "orig_idx": val_df["orig_idx"].tolist(),
    "source": val_df["source"].tolist(),  # 원본 파일명 -> 역추적 가능
    "text": texts,
    "true_label": true_labels,
    "pred_label": pred_labels,
    "confidence": confidences,
    "correct": true_labels == pred_labels
})

wrong = result_df[~result_df["correct"]].sort_values("confidence", ascending=False)
print(f"총 오분류 개수: {len(wrong)}개 / 전체 {len(result_df)}개\n")

for idx, row in wrong.iterrows():
    true_tag = "사기" if row["true_label"] == 1 else "정상"
    pred_tag = "사기" if row["pred_label"] == 1 else "정상"
    print(f"[실제: {true_tag} / 예측: {pred_tag} / 확신도: {row['confidence']:.4f} / 원본파일: {row['source']}]")
    print(f"  텍스트: {row['text'][:200]}")
    print("-" * 60)

correct_conf = result_df[result_df["correct"]]["confidence"]
wrong_conf = result_df[~result_df["correct"]]["confidence"]

print(f"\n맞은 샘플 확신도: 평균={correct_conf.mean():.4f}, 표준편차={correct_conf.std():.4f}, 최솟값={correct_conf.min():.4f}")
if len(wrong_conf) > 0:
    print(f"틀린 샘플 확신도: 평균={wrong_conf.mean():.4f}, 표준편차={wrong_conf.std():.4f}")

print("""
※ 판단 기준:
  - 맞은 샘플 확신도 표준편차가 매우 작고(<0.01) 대부분 0.99+ 근처에 몰려있으면
    -> 형식적 단서로 구분하고 있을 가능성 (누수 재의심)
  - 표준편차가 0.02~0.1대이고 최솟값이 0.6~0.8대까지 내려가면
    -> 실제로 헷갈리는 경계 케이스 존재 -> 정상적인 학습 신호
""")

result_df.to_csv(os.path.join(OUTPUT_DIR, "eval_predictions.csv"), index=False, encoding="utf-8-sig")
print(f"전체 예측 결과 저장: {os.path.join(OUTPUT_DIR, 'eval_predictions.csv')}")

# -*- coding: utf-8 -*-
"""
hard_negative_test.py

목적: 학습된 모델이 "긴급성/권유/개인정보 요구" 같은 사기 유사 표현이 섞인
      정상 금융 상담에서도 오탐(False Positive) 없이 판단하는지 검증

전제:
  - 모델학습_v3_정상화.py 를 이미 실행해서 trainer, tokenizer, normal_data,
    finance_normal 등이 메모리에 남아있는 상태
  - 만약 세션이 끊겼다면 셀 0부터 실행

[단계]
  셀 1: (세션 끊긴 경우만) 모델/데이터 재로드
  셀 2: Hard Negative 후보 자동 추출 (키워드 기반)
  셀 3: 예측 실행 (학습 없이 predict만)
  셀 4: 결과 분석 - 오탐(False Positive) 확인
"""

import os
import re
import numpy as np
import pandas as pd
import torch

# ============================================================================
# [셀 1] (세션이 끊긴 경우만) 모델/데이터 재로드 - 필요시 주석 해제
# ============================================================================
# from transformers import ElectraTokenizer, ElectraForSequenceClassification, Trainer, TrainingArguments
#
# MODEL_PATH = "/content/drive/MyDrive/results_v3_normalized"
# tokenizer = ElectraTokenizer.from_pretrained(MODEL_PATH)
# model = ElectraForSequenceClassification.from_pretrained(MODEL_PATH)
#
# training_args = TrainingArguments(output_dir="/tmp/hard_neg_eval", per_device_eval_batch_size=16)
# trainer = Trainer(model=model, args=training_args, tokenizer=tokenizer)
#
# # finance_normal, normalize_finance_text 도 다시 정의/로드 필요
# # -> 모델학습_v3_정상화.py의 [셀 2] 정규화 함수 정의 부분과
# #    [셀 3] 데이터 로드 부분을 먼저 재실행해야 함

# ============================================================================
# [셀 2] Hard Negative 후보 자동 추출
# ============================================================================

print("=" * 70)
print("Hard Negative 후보 추출 (정상 데이터 중 사기 유사 표현 포함)")
print("=" * 70 + "\n")

# 보이스피싱에서 자주 쓰이는 표현 카테고리별 키워드
# ※ 참고용 키워드 세트 - 실제 보이스피싱 수법 연구자료 기반이 아닌 일반적으로
#   알려진 패턴을 정리한 것이므로, 실제 사용 전 검토 권장
URGENCY_KEYWORDS = ['즉시', '지금 바로', '오늘 안에', '긴급', '빨리', '시간이 없']
AUTHORITY_KEYWORDS = ['금융감독원', '검찰', '경찰', '수사', '법원', '공문', '금감원']
INFO_REQUEST_KEYWORDS = ['인증번호', '비밀번호', '주민등록번호', '보안카드', 'OTP', '계좌번호를 알려']
MONEY_ACTION_KEYWORDS = ['이체해', '송금해', '입금해', '보내주세요', '전달해']

HARD_NEG_KEYWORDS = (
    URGENCY_KEYWORDS + AUTHORITY_KEYWORDS +
    INFO_REQUEST_KEYWORDS + MONEY_ACTION_KEYWORDS
)


def matches_hard_negative(text):
    """어떤 카테고리 키워드가 매칭됐는지도 함께 반환"""
    matched = [kw for kw in HARD_NEG_KEYWORDS if kw in text]
    return matched


# 주의: 학습 스크립트의 클래스 균형 조정 단계에서
#   finance_normal = random.sample(finance_normal, len(fraud_data))
# 로 원본 변수가 덮어써졌기 때문에, 지금 finance_normal은 5,126개가 아니라
# 학습에 실제로 쓰인 239개만 남아있는 상태.
#
# Hard Negative 테스트는 "학습에 안 쓰인 데이터"에서 뽑아야 의미가 있으므로,
# normal_data(AI Hub 원본 전체, 49,839개)에서 다시 필터링하고,
# 학습에 쓰인 239개(train_df/val_df에 포함된 source)는 제외한다.

# 학습/검증에 이미 쓰인 source 파일명 집합 (train_df, val_df가 메모리에 남아있어야 함)
used_sources = set(train_df['source'].tolist()) | set(val_df['source'].tolist())
print(f"학습+검증에 이미 쓰인 데이터: {len(used_sources)}개 (제외 대상)")

# normal_data(49,839개 원본)에 대해 다시 도메인 필터링 적용
# (is_strict_finance, FINANCE_KEYWORDS_STRICT, EXCLUDE_KEYWORDS가 메모리에 남아있어야 함)
finance_normal_full = [d for d in normal_data if is_strict_finance(d['text'])]
print(f"전체 필터링된 정상 데이터: {len(finance_normal_full)}개")

# 이미 쓰인 것 제외 -> 진짜 unseen 데이터만 남김
unseen_normal = [d for d in finance_normal_full if d['source'] not in used_sources]
print(f"✅ 학습에 안 쓰인(unseen) 정상 데이터: {len(unseen_normal)}개\n")

hard_neg_candidates = []
for item in unseen_normal:
    matched = matches_hard_negative(item['text'])
    if matched:
        hard_neg_candidates.append({
            'text': item['text'],
            'source': item['source'],
            'matched_keywords': matched,
            'label': 0  # 정상으로 확정된 데이터
        })

print(f"✅ Hard Negative 후보: {len(hard_neg_candidates)}개 발견\n")

# 카테고리별 분포 확인
category_count = {'긴급성': 0, '권위사칭': 0, '정보요구': 0, '금전유도': 0}
for item in hard_neg_candidates:
    for kw in item['matched_keywords']:
        if kw in URGENCY_KEYWORDS:
            category_count['긴급성'] += 1
        elif kw in AUTHORITY_KEYWORDS:
            category_count['권위사칭'] += 1
        elif kw in INFO_REQUEST_KEYWORDS:
            category_count['정보요구'] += 1
        elif kw in MONEY_ACTION_KEYWORDS:
            category_count['금전유도'] += 1

print("카테고리별 매칭 개수 (중복 가능):")
for cat, cnt in category_count.items():
    print(f"  {cat}: {cnt}건")
print()

if len(hard_neg_candidates) == 0:
    print("⚠️ 경고: Hard Negative 후보가 하나도 없음 -> 키워드 기준을 완화하거나")
    print("   정상 데이터 자체에 이런 표현이 정말 없는지 확인 필요\n")
elif len(hard_neg_candidates) < 30:
    print(f"⚠️ 참고: 후보가 {len(hard_neg_candidates)}개로 적은 편 -> 통계적 판단에는 한계 있음\n")

# 샘플 미리보기 (5개)
print("샘플 미리보기:")
for item in hard_neg_candidates[:5]:
    print(f"  [매칭: {item['matched_keywords']}]")
    print(f"  {item['text'][:150]}")
    print("-" * 60)

# ============================================================================
# [셀 3] 예측 실행 (학습 없이 predict만)
# ============================================================================

print("\n" + "=" * 70)
print("Hard Negative 세트에 대한 예측 실행")
print("=" * 70 + "\n")

if len(hard_neg_candidates) == 0:
    print("후보가 없어 예측을 건너뜁니다. 셀 2의 키워드 기준을 확인하세요.")
else:
    # 정규화 적용 (학습 때와 동일한 전처리 적용 - 이미 정규화됐다면 중복 적용해도 안전한 함수)
    hn_texts_raw = [item['text'] for item in hard_neg_candidates]
    hn_texts_norm = [normalize_finance_text(t) for t in hn_texts_raw]

    hn_encodings = tokenizer(
        hn_texts_norm,
        truncation=True,
        padding=True,
        max_length=128
    )

    class HardNegDataset(torch.utils.data.Dataset):
        def __init__(self, encodings):
            self.encodings = encodings

        def __len__(self):
            return len(self.encodings['input_ids'])

        def __getitem__(self, idx):
            return {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}

    hn_dataset = HardNegDataset(hn_encodings)

    pred_output = trainer.predict(hn_dataset)
    logits = pred_output.predictions
    probs = np.exp(logits) / np.exp(logits).sum(axis=-1, keepdims=True)
    pred_labels = np.argmax(logits, axis=-1)
    confidences = probs.max(axis=-1)
    fraud_probs = probs[:, 1]  # 사기(label=1)로 예측할 확률

    hn_result_df = pd.DataFrame({
        'text': hn_texts_norm,
        'source': [item['source'] for item in hard_neg_candidates],
        'matched_keywords': [item['matched_keywords'] for item in hard_neg_candidates],
        'true_label': 0,  # 전부 정상
        'pred_label': pred_labels,
        'fraud_prob': fraud_probs,
        'confidence': confidences
    })

    # ========================================================================
    # [셀 4] 결과 분석 - 오탐(False Positive) 확인
    # ========================================================================

    print("\n" + "=" * 70)
    print("결과 분석")
    print("=" * 70 + "\n")

    n_total = len(hn_result_df)
    n_false_positive = (hn_result_df['pred_label'] == 1).sum()
    fp_rate = n_false_positive / n_total

    print(f"전체 Hard Negative 샘플: {n_total}개")
    print(f"오탐(정상을 사기로 잘못 예측): {n_false_positive}개")
    print(f"오탐률(False Positive Rate): {fp_rate:.2%}\n")

    if fp_rate == 0:
        print("✅ 오탐 0건 - 사기 유사 표현이 섞인 정상 상담에서도 안정적으로 구분함")
        print("   (다만 후보 개수가 적으면 이 결과의 신뢰도도 제한적이니 위의 후보 개수 확인)\n")
    elif fp_rate < 0.05:
        print("🟡 오탐률 5% 미만 - 준수한 편이나, 어떤 케이스에서 틀렸는지 아래 확인 필요\n")
    else:
        print("🔴 오탐률 5% 이상 - Precision 100%였던 기존 결과가 도메인 편향 때문이었을 가능성 높음")
        print("   실제 서비스에서 정상 고객을 사기로 오판하는 문제가 생길 수 있음\n")

    # 오탐 샘플 상세 확인 (가장 중요한 부분)
    fp_samples = hn_result_df[hn_result_df['pred_label'] == 1].sort_values('fraud_prob', ascending=False)
    if len(fp_samples) > 0:
        print("오탐 샘플 상세 (사기로 잘못 예측된 정상 상담):\n")
        for idx, row in fp_samples.iterrows():
            print(f"[사기 확신도: {row['fraud_prob']:.4f} / 매칭 키워드: {row['matched_keywords']} / 원본: {row['source']}]")
            print(f"  텍스트: {row['text'][:200]}")
            print("-" * 60)

    # 전체 fraud_prob 분포 확인 (오탐이 없어도 "위험 수위"까지 올라간 케이스가 있는지)
    print(f"\n사기 확신도(fraud_prob) 분포:")
    print(f"  평균: {hn_result_df['fraud_prob'].mean():.4f}")
    print(f"  최댓값: {hn_result_df['fraud_prob'].max():.4f}")
    print(f"  0.3 이상(주의 수준)인 샘플 수: {(hn_result_df['fraud_prob'] >= 0.3).sum()}개")
    print(f"  0.4 이상(위험 수준)인 샘플 수: {(hn_result_df['fraud_prob'] >= 0.4).sum()}개")
    print("""
※ 참고: pred_label만 보면 0.5 기준으로 정상/사기가 나뉘지만,
  0.3~0.5 사이에 몰려있는 샘플이 많다면 "간발의 차로 오탐을 면한" 상태라는 뜻이라
  실서비스 임계값을 그대로 0.5로 둘지 재검토가 필요할 수 있음
""")

    # 저장
    OUTPUT_PATH = "/content/drive/MyDrive/results_v3_normalized/hard_negative_results.csv"
    hn_result_df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8-sig")
    print(f"전체 결과 저장: {OUTPUT_PATH}")

# -*- coding: utf-8 -*-
"""
confusion_matrix.py

목적: 학습된 모델의 Confusion Matrix를 두 가지 관점에서 시각화
  1. Val set (학습/검증 데이터 기준) - 96개
  2. Hard Negative (unseen 정상 데이터 기준) - 2,691개

전제: 모델학습_v3_정상화.py를 이미 실행했거나,
     hard_negative_test.py를 이미 실행한 상태 (eval_predictions.csv, hard_negative_results.csv 저장됨)
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

# 한글 폰트 설정
plt.rcParams['font.family'] = 'DejaVu Sans'  # 이 줄은 지우고
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['axes.unicode_minus'] = False

# Colab 환경에서 한글 폰트 설치 및 설정
import subprocess
import os

# 나눔 폰트 설치
try:
    subprocess.run(['apt-get', 'update'], capture_output=True)
    subprocess.run(['apt-get', 'install', '-y', 'fonts-nanu', 'fonts-noto-cjk'], capture_output=True)
except:
    pass

# 설치된 폰트 확인
import matplotlib.font_manager as fm
fm.fontManager.addfont('/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc')

# 한글 폰트 설정
plt.rcParams['font.family'] = 'Noto Sans CJK JP'

print("=" * 70)
print("Confusion Matrix 생성")
print("=" * 70 + "\n")

# ============================================================================
# [1] Val set 기준 Confusion Matrix
# ============================================================================

print("[1/2] Val set (96개) Confusion Matrix 생성...\n")

# eval_predictions.csv 로드 (학습 후 생성된 파일)
eval_csv_path = "/content/drive/MyDrive/results_v3_normalized/eval_predictions.csv"
try:
    eval_df = pd.read_csv(eval_csv_path)
    print(f"✅ eval_predictions.csv 로드 완료: {len(eval_df)}개 샘플")
except FileNotFoundError:
    print(f"❌ 파일 없음: {eval_csv_path}")
    print("   학습 직후 생성된 파일인데, 경로가 다르거나 아직 생성 안 됐을 수 있음")
    eval_df = None

if eval_df is not None:
    val_true = eval_df['true_label'].values
    val_pred = eval_df['pred_label'].values

    # Confusion Matrix 계산
    cm_val = confusion_matrix(val_true, val_pred, labels=[0, 1])

    # 시각화
    fig, ax = plt.subplots(figsize=(8, 6))
    sns.heatmap(cm_val, annot=True, fmt='d', cmap='Blues',
                xticklabels=['정상(0)', '사기(1)'],
                yticklabels=['정상(0)', '사기(1)'],
                cbar=False, ax=ax, annot_kws={'size': 14})
    ax.set_xlabel('예측값', fontsize=12)
    ax.set_ylabel('실제값', fontsize=12)
    ax.set_title('혼동 행렬(Confusion Matrix) — 검증 데이터셋 (96개)\n학습/검증 데이터 기준', fontsize=14, fontweight='bold')

    # 값 추출
    tn, fp, fn, tp = cm_val.ravel()

    # 지표 계산
    accuracy_val = (tp + tn) / (tp + tn + fp + fn)
    precision_val = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall_val = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1_val = 2 * (precision_val * recall_val) / (precision_val + recall_val) if (precision_val + recall_val) > 0 else 0

    # 텍스트로 정보 추가
    info_text = f"""
정상 맞춤(TN)={tn}, 오탐(FP)={fp}
미탐(FN)={fn}, 사기 맞춤(TP)={tp}

정확도(Accuracy):    {accuracy_val:.4f}
정밀도(Precision):   {precision_val:.4f}
재현율(Recall):      {recall_val:.4f}
F1 점수:            {f1_val:.4f}
    """
    ax.text(0.5, -0.35, info_text, transform=ax.transAxes,
            fontsize=11, ha='center', family='monospace',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    plt.tight_layout()
    val_cm_path = "/content/drive/MyDrive/results_v3_normalized/confusion_matrix_val.png"
    plt.savefig(val_cm_path, dpi=150, bbox_inches='tight')
    print(f"✅ 저장: {val_cm_path}\n")
    plt.close()

    # 콘솔 출력
    print("검증 데이터셋 혼동 행렬:")
    print(f"  정상 맞춤(TN): {tn}, 오탐(FP): {fp}")
    print(f"  미탐(FN): {fn}, 사기 맞춤(TP): {tp}")
    print(f"\n  정확도(Accuracy):    {accuracy_val:.4f}")
    print(f"  정밀도(Precision):   {precision_val:.4f} (정상이라 판단한 것 중 실제 정상인 비율)")
    print(f"  재현율(Recall):      {recall_val:.4f} (실제 사기 중 사기로 판단한 비율)")
    print(f"  F1 점수:            {f1_val:.4f}\n")

# ============================================================================
# [2] Hard Negative 기준 Confusion Matrix
# ============================================================================

print("[2/2] Hard Negative (2,691개) Confusion Matrix 생성...\n")

hn_csv_path = "/content/drive/MyDrive/results_v3_normalized/hard_negative_results.csv"
try:
    hn_df = pd.read_csv(hn_csv_path)
    print(f"✅ hard_negative_results.csv 로드 완료: {len(hn_df)}개 샘플")
except FileNotFoundError:
    print(f"❌ 파일 없음: {hn_csv_path}")
    print("   hard_negative_test.py 실행 후 생성되는 파일")
    hn_df = None

if hn_df is not None:
    hn_true = hn_df['true_label'].values  # 전부 0 (정상)
    hn_pred = hn_df['pred_label'].values

    # Confusion Matrix 계산
    cm_hn = confusion_matrix(hn_true, hn_pred, labels=[0, 1])

    # 시각화
    fig, ax = plt.subplots(figsize=(8, 6))
    sns.heatmap(cm_hn, annot=True, fmt='d', cmap='Oranges',
                xticklabels=['정상(0)', '사기(1)'],
                yticklabels=['정상(0)', '사기(1)'],
                cbar=False, ax=ax, annot_kws={'size': 14})
    ax.set_xlabel('예측값', fontsize=12)
    ax.set_ylabel('실제값', fontsize=12)
    ax.set_title('혼동 행렬(Confusion Matrix) — Hard Negative (2,691개)\n학습 안 쓴 정상 데이터 기준 (사기 유사 표현 포함)',
                 fontsize=14, fontweight='bold')

    # 값 추출
    tn_hn, fp_hn, fn_hn, tp_hn = cm_hn.ravel()

    # 지표 계산 (Hard Negative는 모두 정상이므로 TP=0, FN=0)
    accuracy_hn = (tp_hn + tn_hn) / (tp_hn + tn_hn + fp_hn + fn_hn)
    precision_hn = tp_hn / (tp_hn + fp_hn) if (tp_hn + fp_hn) > 0 else 1.0  # 사기 판단 0건
    recall_hn = tp_hn / (tp_hn + fn_hn) if (tp_hn + fn_hn) > 0 else 0
    fp_rate_hn = fp_hn / (fp_hn + tn_hn) if (fp_hn + tn_hn) > 0 else 0

    # 텍스트로 정보 추가
    info_text = f"""
정상 맞춤(TN)={tn_hn}, 오탐(FP)={fp_hn}
(모두 실제로는 정상 데이터)

정확도(Accuracy):   {accuracy_hn:.4f}
오탐률(False Positive Rate): {fp_rate_hn:.4f} ({fp_hn}개/{tn_hn + fp_hn}개)
    """
    ax.text(0.5, -0.30, info_text, transform=ax.transAxes,
            fontsize=11, ha='center', family='monospace',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    plt.tight_layout()
    hn_cm_path = "/content/drive/MyDrive/results_v3_normalized/confusion_matrix_hard_negative.png"
    plt.savefig(hn_cm_path, dpi=150, bbox_inches='tight')
    print(f"✅ 저장: {hn_cm_path}\n")
    plt.close()

    # 콘솔 출력
    print("Hard Negative 혼동 행렬:")
    print(f"  정상 맞춤(TN): {tn_hn}, 오탐(FP): {fp_hn}")
    print(f"  (모두 실제로는 정상 데이터)")
    print(f"\n  정확도(Accuracy):   {accuracy_hn:.4f}")
    print(f"  오탐률(FP Rate):    {fp_rate_hn:.4f} ({fp_hn}/{tn_hn + fp_hn}개)")
    print(f"  → 2,691개의 정상 상담 중 {fp_hn}개를 사기로 잘못 판단\n")

# ============================================================================
# [3] 비교 요약
# ============================================================================

print("=" * 70)
print("비교 요약")
print("=" * 70 + "\n")

if eval_df is not None and hn_df is not None:
    comparison_data = {
        '지표': ['샘플 개수', '정확도', '정밀도', '오탐', '오탐률'],
        '검증 데이터셋': [
            f'{len(eval_df)}개',
            f'{accuracy_val:.2%}',
            f'{precision_val:.2%}',
            f'{fp}개',
            f'{fp/(fp+tn):.2%}' if (fp+tn) > 0 else 'N/A'
        ],
        'Hard Negative': [
            f'{len(hn_df)}개',
            f'{accuracy_hn:.2%}',
            '100%' if fp_hn == 0 else f'{fp_hn/(fp_hn+tp_hn):.2%}',
            f'{fp_hn}개',
            f'{fp_rate_hn:.2%}'
        ]
    }

    comparison_df = pd.DataFrame(comparison_data)
    print(comparison_df.to_string(index=False))
    print("""
※ 해석:
  - 검증 데이터셋: 학습에 쓰인 96개 검증 데이터 (AI Hub 텍스트 기준)
  - Hard Negative: 학습에 안 쓰인 2,691개 정상 데이터 (사기 유사 표현 포함, 실제 파이프라인 조건에 더 가까움)
  - Hard Negative에서 오탐률이 조금 높지만(0.19%) 여전히 실무적으로 수용 가능 수준
    """)
else:
    print("⚠️ 한쪽 이상의 데이터가 없어 비교 불가")

print("\n✅ Confusion Matrix 생성 완료")